import Navbar from "../Navbar/Navbar.js";
import NavbarSm from "../Navbar/NavbarSm.js";
import NavbarSmTop from "../Navbar/NavbarSmTop.js";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>hobï</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <NavbarSm />
      <NavbarSmTop />
      {children}
    </>
  );
};

export default Layout;
