//* Description: This is the home page of the site

// Import statements
import React from 'react';
import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import '../styles/Home.module.css';

// Component imports
import Navbar from '../components/Navbar/Navbar';

// Home component
export default function Home() {
  return (
    <>
      <Head>
        <title>Site being built</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="md:mt-28 z-1 absolute w-full flex-col items-center justify-center px-6 md:px-12">
          <h1 className="text-5xl md:text-7xl mt-6 md:mt-0 font-bold">
            Learn (almost) anything!
          </h1>
          <p className="md:w-2/3 pt-2 font-serif text-base md:text-xl">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat.
          </p>
          <div className="flex items-center gap-6 pt-3 md:mt-3 text-2xl">
            <Link
              className="rounded-full border-2 text-base md:text-2xl border-indigo-700 py-1 px-4 transition ease-in-out hover:bg-indigo-400 hover:bg-opacity-50"
              href="/explore"
            >
              EXPLORE
            </Link>
            <Link
              className="text-indigo-700 text-base md:text-2xl transition ease-in-out"
              href="/about"
            >
              ABOUT
            </Link>
          </div>
          <div className="z-0 flex w-full md:right-0 md:w-2/3">
            <img src="/team-work.svg" alt="home" />
          </div>
        </div>
      </main>
    </>
  );
}
